INSERT INTO status (status) VALUES ('Finished');
INSERT INTO status (status) VALUES ('Disqualified');
INSERT INTO status (status) VALUES ('Accident');
INSERT INTO status (status) VALUES ('Collision');
INSERT INTO status (status) VALUES ('Engine');
INSERT INTO status (status) VALUES ('Gearbox');
INSERT INTO status (status) VALUES ('Transmission');
INSERT INTO status (status) VALUES ('Clutch');
INSERT INTO status (status) VALUES ('Hydraulics');
INSERT INTO status (status) VALUES ('Electrical');
INSERT INTO status (status) VALUES ('+1 Lap');
INSERT INTO status (status) VALUES ('+2 Laps');
INSERT INTO status (status) VALUES ('+3 Laps');
INSERT INTO status (status) VALUES ('+4 Laps');
INSERT INTO status (status) VALUES ('+5 Laps');
INSERT INTO status (status) VALUES ('+6 Laps');
INSERT INTO status (status) VALUES ('+7 Laps');
INSERT INTO status (status) VALUES ('+8 Laps');
INSERT INTO status (status) VALUES ('+9 Laps');
INSERT INTO status (status) VALUES ('Spun off');
INSERT INTO status (status) VALUES ('Radiator');
INSERT INTO status (status) VALUES ('Suspension');
INSERT INTO status (status) VALUES ('Brakes');
INSERT INTO status (status) VALUES ('Differential');
INSERT INTO status (status) VALUES ('Overheating');
INSERT INTO status (status) VALUES ('Mechanical');
INSERT INTO status (status) VALUES ('Tyre');
INSERT INTO status (status) VALUES ('Driver Seat');
INSERT INTO status (status) VALUES ('Puncture');
INSERT INTO status (status) VALUES ('Driveshaft');
INSERT INTO status (status) VALUES ('Retired');
INSERT INTO status (status) VALUES ('Fuel pressure');
INSERT INTO status (status) VALUES ('Front wing');
INSERT INTO status (status) VALUES ('Water pressure');
INSERT INTO status (status) VALUES ('Refuelling');
INSERT INTO status (status) VALUES ('Wheel');
INSERT INTO status (status) VALUES ('Throttle');
INSERT INTO status (status) VALUES ('Steering');
INSERT INTO status (status) VALUES ('Technical');
INSERT INTO status (status) VALUES ('Electronics');
INSERT INTO status (status) VALUES ('Broken wing');
INSERT INTO status (status) VALUES ('Heat shield fire');
INSERT INTO status (status) VALUES ('Exhaust');
INSERT INTO status (status) VALUES ('Oil leak');
INSERT INTO status (status) VALUES ('+11 Laps');
INSERT INTO status (status) VALUES ('Wheel rim');
INSERT INTO status (status) VALUES ('Water leak');
INSERT INTO status (status) VALUES ('Fuel pump');
INSERT INTO status (status) VALUES ('Track rod');
INSERT INTO status (status) VALUES ('+17 Laps');
INSERT INTO status (status) VALUES ('Oil pressure');
INSERT INTO status (status) VALUES ('+42 Laps');
INSERT INTO status (status) VALUES ('+13 Laps');
INSERT INTO status (status) VALUES ('Withdrew');
INSERT INTO status (status) VALUES ('+12 Laps');
INSERT INTO status (status) VALUES ('Engine fire');
INSERT INTO status (status) VALUES ('Engine misfire');
INSERT INTO status (status) VALUES ('+26 Laps');
INSERT INTO status (status) VALUES ('Tyre puncture');
INSERT INTO status (status) VALUES ('Out of fuel');
INSERT INTO status (status) VALUES ('Wheel nut');
INSERT INTO status (status) VALUES ('Not classified');
INSERT INTO status (status) VALUES ('Pneumatics');
INSERT INTO status (status) VALUES ('Handling');
INSERT INTO status (status) VALUES ('Rear wing');
INSERT INTO status (status) VALUES ('Fire');
INSERT INTO status (status) VALUES ('Wheel bearing');
INSERT INTO status (status) VALUES ('Physical');
INSERT INTO status (status) VALUES ('Fuel system');
INSERT INTO status (status) VALUES ('Oil line');
INSERT INTO status (status) VALUES ('Fuel rig');
INSERT INTO status (status) VALUES ('Launch control');
INSERT INTO status (status) VALUES ('Injured');
INSERT INTO status (status) VALUES ('Fuel');
INSERT INTO status (status) VALUES ('Power loss');
INSERT INTO status (status) VALUES ('Vibrations');
INSERT INTO status (status) VALUES ('107% Rule');
INSERT INTO status (status) VALUES ('Safety');
INSERT INTO status (status) VALUES ('Drivetrain');
INSERT INTO status (status) VALUES ('Ignition');
INSERT INTO status (status) VALUES ('Did not qualify');
INSERT INTO status (status) VALUES ('Injury');
INSERT INTO status (status) VALUES ('Chassis');
INSERT INTO status (status) VALUES ('Battery');
INSERT INTO status (status) VALUES ('Stalled');
INSERT INTO status (status) VALUES ('Halfshaft');
INSERT INTO status (status) VALUES ('Crankshaft');
INSERT INTO status (status) VALUES ('+10 Laps');
INSERT INTO status (status) VALUES ('Safety concerns');
INSERT INTO status (status) VALUES ('Not restarted');
INSERT INTO status (status) VALUES ('Alternator');
INSERT INTO status (status) VALUES ('Underweight');
INSERT INTO status (status) VALUES ('Safety belt');
INSERT INTO status (status) VALUES ('Oil pump');
INSERT INTO status (status) VALUES ('Fuel leak');
INSERT INTO status (status) VALUES ('Excluded');
INSERT INTO status (status) VALUES ('Did not prequalify');
INSERT INTO status (status) VALUES ('Injection');
INSERT INTO status (status) VALUES ('Distributor');
INSERT INTO status (status) VALUES ('Driver unwell');
INSERT INTO status (status) VALUES ('Turbo');
INSERT INTO status (status) VALUES ('CV joint');
INSERT INTO status (status) VALUES ('Water pump');
INSERT INTO status (status) VALUES ('Fatal accident');
INSERT INTO status (status) VALUES ('Spark plugs');
INSERT INTO status (status) VALUES ('Fuel pipe');
INSERT INTO status (status) VALUES ('Eye injury');
INSERT INTO status (status) VALUES ('Oil pipe');
INSERT INTO status (status) VALUES ('Axle');
INSERT INTO status (status) VALUES ('Water pipe');
INSERT INTO status (status) VALUES ('+14 Laps');
INSERT INTO status (status) VALUES ('+15 Laps');
INSERT INTO status (status) VALUES ('+25 Laps');
INSERT INTO status (status) VALUES ('+18 Laps');
INSERT INTO status (status) VALUES ('+22 Laps');
INSERT INTO status (status) VALUES ('+16 Laps');
INSERT INTO status (status) VALUES ('+24 Laps');
INSERT INTO status (status) VALUES ('+29 Laps');
INSERT INTO status (status) VALUES ('+23 Laps');
INSERT INTO status (status) VALUES ('+21 Laps');
INSERT INTO status (status) VALUES ('Magneto');
INSERT INTO status (status) VALUES ('+44 Laps');
INSERT INTO status (status) VALUES ('+30 Laps');
INSERT INTO status (status) VALUES ('+19 Laps');
INSERT INTO status (status) VALUES ('+46 Laps');
INSERT INTO status (status) VALUES ('Supercharger');
INSERT INTO status (status) VALUES ('+20 Laps');
INSERT INTO status (status) VALUES ('Collision damage');
INSERT INTO status (status) VALUES ('Power Unit');
INSERT INTO status (status) VALUES ('ERS');
INSERT INTO status (status) VALUES ('+49 Laps');
INSERT INTO status (status) VALUES ('+38 Laps');
INSERT INTO status (status) VALUES ('Brake duct');
INSERT INTO status (status) VALUES ('Seat');
INSERT INTO status (status) VALUES ('Damage');
INSERT INTO status (status) VALUES ('Debris');
INSERT INTO status (status) VALUES ('Illness');
INSERT INTO status (status) VALUES ('Undertray');
INSERT INTO status (status) VALUES ('Cooling system');
