INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('mclaren', 'McLaren', 'British', 'http://en.wikipedia.org/wiki/McLaren');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('bmw_sauber', 'BMW Sauber', 'German', 'http://en.wikipedia.org/wiki/BMW_Sauber');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('williams', 'Williams', 'British', 'http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('renault', 'Renault', 'French', 'http://en.wikipedia.org/wiki/Renault_in_Formula_One');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('toro_rosso', 'Toro Rosso', 'Italian', 'http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('ferrari', 'Ferrari', 'Italian', 'http://en.wikipedia.org/wiki/Scuderia_Ferrari');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('toyota', 'Toyota', 'Japanese', 'http://en.wikipedia.org/wiki/Toyota_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('super_aguri', 'Super Aguri', 'Japanese', 'http://en.wikipedia.org/wiki/Super_Aguri_F1');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('red_bull', 'Red Bull', 'Austrian', 'http://en.wikipedia.org/wiki/Red_Bull_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('force_india', 'Force India', 'Indian', 'http://en.wikipedia.org/wiki/Racing_Point_Force_India');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('honda', 'Honda', 'Japanese', 'http://en.wikipedia.org/wiki/Honda_Racing_F1');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('spyker', 'Spyker', 'Dutch', 'http://en.wikipedia.org/wiki/Spyker_F1');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('mf1', 'MF1', 'Russian', 'http://en.wikipedia.org/wiki/Midland_F1_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('spyker_mf1', 'Spyker MF1', 'Dutch', 'http://en.wikipedia.org/wiki/Midland_F1_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('sauber', 'Sauber', 'Swiss', 'http://en.wikipedia.org/wiki/Sauber_Motorsport');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('bar', 'BAR', 'British', 'http://en.wikipedia.org/wiki/British_American_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('jordan', 'Jordan', 'Irish', 'http://en.wikipedia.org/wiki/Jordan_Grand_Prix');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('minardi', 'Minardi', 'Italian', 'http://en.wikipedia.org/wiki/Minardi');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('jaguar', 'Jaguar', 'British', 'http://en.wikipedia.org/wiki/Jaguar_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('prost', 'Prost', 'French', 'http://en.wikipedia.org/wiki/Prost_Grand_Prix');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('arrows', 'Arrows', 'British', 'http://en.wikipedia.org/wiki/Arrows_Grand_Prix_International');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('benetton', 'Benetton', 'Italian', 'http://en.wikipedia.org/wiki/Benetton_Formula');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brawn', 'Brawn', 'British', 'http://en.wikipedia.org/wiki/Brawn_GP');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('stewart', 'Stewart', 'British', 'http://en.wikipedia.org/wiki/Stewart_Grand_Prix');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('tyrrell', 'Tyrrell', 'British', 'http://en.wikipedia.org/wiki/Tyrrell_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lola', 'Lola', 'British', 'http://en.wikipedia.org/wiki/MasterCard_Lola');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('ligier', 'Ligier', 'French', 'http://en.wikipedia.org/wiki/Ligier');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('forti', 'Forti', 'Italian', 'http://en.wikipedia.org/wiki/Forti');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('footwork', 'Footwork', 'British', 'http://en.wikipedia.org/wiki/Footwork_Arrows');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('pacific', 'Pacific', 'British', 'http://en.wikipedia.org/wiki/Pacific_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('simtek', 'Simtek', 'British', 'http://en.wikipedia.org/wiki/Simtek');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('team_lotus', 'Team Lotus', 'British', 'http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('larrousse', 'Larrousse', 'French', 'http://en.wikipedia.org/wiki/Larrousse');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brabham', 'Brabham', 'British', 'http://en.wikipedia.org/wiki/Brabham');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('dallara', 'Dallara', 'Italian', 'http://en.wikipedia.org/wiki/Dallara');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('fondmetal', 'Fondmetal', 'Italian', 'http://en.wikipedia.org/wiki/Fondmetal');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('march', 'March', 'British', 'http://en.wikipedia.org/wiki/March_Engineering');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('moda', 'Andrea Moda', 'Italian', 'http://en.wikipedia.org/wiki/Andrea_Moda_Formula');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('ags', 'AGS', 'French', 'http://en.wikipedia.org/wiki/Automobiles_Gonfaronnaises_Sportives');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lambo', 'Lambo', 'Italian', 'http://en.wikipedia.org/wiki/Modena_(racing_team)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('leyton', 'Leyton House', 'British', 'http://en.wikipedia.org/wiki/Leyton_House');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('coloni', 'Coloni', 'Italian', 'http://en.wikipedia.org/wiki/Enzo_Coloni_Racing_Car_Systems');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('eurobrun', 'Euro Brun', 'Italian', 'http://en.wikipedia.org/wiki/Euro_Brun');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('osella', 'Osella', 'Italian', 'http://en.wikipedia.org/wiki/Osella');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('onyx', 'Onyx', 'British', 'http://en.wikipedia.org/wiki/Onyx_(racing_team)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('life', 'Life', 'Italian', 'http://en.wikipedia.org/wiki/Life_(Racing_Team)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('rial', 'Rial', 'German', 'http://en.wikipedia.org/wiki/Rial_%28racing_team%29');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('zakspeed', 'Zakspeed', 'German', 'http://en.wikipedia.org/wiki/Zakspeed');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('ram', 'RAM', 'British', 'http://en.wikipedia.org/wiki/RAM_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('alfa', 'Alfa Romeo', 'Swiss', 'http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('spirit', 'Spirit', 'British', 'http://en.wikipedia.org/wiki/Spirit_(racing_team)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('toleman', 'Toleman', 'British', 'http://en.wikipedia.org/wiki/Toleman');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('ats', 'ATS', 'Italian', 'http://en.wikipedia.org/wiki/ATS_(wheels)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('theodore', 'Theodore', 'Hong Kong', 'http://en.wikipedia.org/wiki/Theodore_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('fittipaldi', 'Fittipaldi', 'Brazilian', 'http://en.wikipedia.org/wiki/Fittipaldi_%28constructor%29');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('ensign', 'Ensign', 'British', 'http://en.wikipedia.org/wiki/Ensign_%28racing_team%29');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('shadow', 'Shadow', 'British', 'http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('wolf', 'Wolf', 'Canadian', 'http://en.wikipedia.org/wiki/Walter_Wolf_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('merzario', 'Merzario', 'Italian', 'http://en.wikipedia.org/wiki/Merzario');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('kauhsen', 'Kauhsen', 'German', 'http://en.wikipedia.org/wiki/Kauhsen');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('rebaque', 'Rebaque', 'Mexican', 'http://en.wikipedia.org/wiki/Rebaque');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('surtees', 'Surtees', 'British', 'http://en.wikipedia.org/wiki/Surtees');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('hesketh', 'Hesketh', 'British', 'http://en.wikipedia.org/wiki/Hesketh_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('martini', 'Martini', 'French', 'http://en.wikipedia.org/wiki/Martini_(cars)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brm', 'BRM', 'British', 'http://en.wikipedia.org/wiki/BRM');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('penske', 'Penske', 'American', 'http://en.wikipedia.org/wiki/Penske_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lec', 'LEC', 'British', 'http://en.wikipedia.org/wiki/LEC_(Formula_One)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('mcguire', 'McGuire', 'Australian', 'http://en.wikipedia.org/wiki/McGuire_(Formula_One)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('boro', 'Boro', 'Dutch', 'http://en.wikipedia.org/wiki/Boro_(Formula_One)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('apollon', 'Apollon', 'Swiss', 'http://en.wikipedia.org/wiki/Apollon_(Formula_One)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('kojima', 'Kojima', 'Japanese', 'http://en.wikipedia.org/wiki/Kojima_Engineering');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('parnelli', 'Parnelli', 'American', 'http://en.wikipedia.org/wiki/Parnelli');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('maki', 'Maki', 'Japanese', 'http://en.wikipedia.org/wiki/Maki_(cars)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('hill', 'Embassy Hill', 'British', 'http://en.wikipedia.org/wiki/Hill_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lyncar', 'Lyncar', 'British', 'http://en.wikipedia.org/wiki/Lyncar');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('trojan', 'Trojan', 'British', 'http://en.wikipedia.org/wiki/Trojan_(Racing_team)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('amon', 'Amon', 'New Zealander', 'http://en.wikipedia.org/wiki/Amon_(Formula_One_team)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('token', 'Token', 'British', 'http://en.wikipedia.org/wiki/Token_(Racing_team)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('iso_marlboro', 'Iso Marlboro', 'British', 'http://en.wikipedia.org/wiki/Iso_Marlboro');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('tecno', 'Tecno', 'Italian', 'http://en.wikipedia.org/wiki/Tecno');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('matra', 'Matra', 'French', 'http://en.wikipedia.org/wiki/Matra');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('politoys', 'Politoys', 'British', 'http://en.wikipedia.org/wiki/Frank_Williams_Racing_Cars');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('connew', 'Connew', 'British', 'http://en.wikipedia.org/wiki/Connew');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('bellasi', 'Bellasi', 'Swiss', 'http://en.wikipedia.org/wiki/Bellasi');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('tomaso', 'De Tomaso', 'Italian', 'http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper', 'Cooper', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('eagle', 'Eagle', 'American', 'http://en.wikipedia.org/wiki/Anglo_American_Racers');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lds', 'LDS', 'South African', 'http://en.wikipedia.org/wiki/LDS_(automobile)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('protos', 'Protos', 'British', 'http://en.wikipedia.org/wiki/Protos_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('shannon', 'Shannon', 'British', 'http://en.wikipedia.org/wiki/Shannon_(Formula_One)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('scirocco', 'Scirocco', 'British', 'http://en.wikipedia.org/wiki/Scirocco-Powell');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('re', 'RE', 'Rhodesian', 'http://en.wikipedia.org/wiki/RE_%28automobile%29');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brp', 'BRP', 'British', 'http://en.wikipedia.org/wiki/British_Racing_Partnership');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('porsche', 'Porsche', 'German', 'http://en.wikipedia.org/wiki/Porsche_in_Formula_One');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('derrington', 'Derrington', 'British', 'http://en.wikipedia.org/wiki/Derrington-Francis');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('gilby', 'Gilby', 'British', 'http://en.wikipedia.org/wiki/Gilby');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('stebro', 'Stebro', 'Canadian', 'http://en.wikipedia.org/wiki/Stebro');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('emeryson', 'Emeryson', 'British', 'http://en.wikipedia.org/wiki/Emeryson');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('enb', 'ENB', 'Belgian', 'http://en.wikipedia.org/wiki/Ecurie_Nationale_Belge');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('jbw', 'JBW', 'British', 'http://en.wikipedia.org/wiki/JBW');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('ferguson', 'Ferguson', 'British', 'http://en.wikipedia.org/wiki/Ferguson_Research_Ltd.');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('mbm', 'MBM', 'Swiss', 'http://en.wikipedia.org/wiki/Monteverdi_Basel_Motors');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('behra-porsche', 'Behra-Porsche', 'Italian', 'http://en.wikipedia.org/wiki/Behra-Porsche');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('maserati', 'Maserati', 'Italian', 'http://en.wikipedia.org/wiki/Maserati');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('scarab', 'Scarab', 'American', 'http://en.wikipedia.org/wiki/Scarab_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('watson', 'Watson', 'American', 'http://en.wikipedia.org/wiki/A.J._Watson');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('epperly', 'Epperly', 'American', 'http://en.wikipedia.org/wiki/Epperly');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('phillips', 'Phillips', 'American', 'http://en.wikipedia.org/wiki/Phillips_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lesovsky', 'Lesovsky', 'American', 'http://en.wikipedia.org/wiki/Lesovsky');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('trevis', 'Trevis', 'American', 'http://en.wikipedia.org/wiki/Trevis');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('meskowski', 'Meskowski', 'American', 'http://en.wikipedia.org/wiki/Meskowski');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('kurtis_kraft', 'Kurtis Kraft', 'American', 'http://en.wikipedia.org/wiki/Kurtis_Kraft');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('kuzma', 'Kuzma', 'American', 'http://en.wikipedia.org/wiki/Kuzma_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('vhristensen', 'Christensen', 'American', 'http://en.wikipedia.org/wiki/Christensen_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('ewing', 'Ewing', 'American', 'http://en.wikipedia.org/wiki/Ewing_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('aston_martin', 'Aston Martin', 'British', 'http://en.wikipedia.org/wiki/Aston_Martin_in_Formula_One');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('vanwall', 'Vanwall', 'British', 'http://en.wikipedia.org/wiki/Vanwall');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('moore', 'Moore', 'American', 'http://en.wikipedia.org/wiki/Moore_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('dunn', 'Dunn', 'American', 'http://en.wikipedia.org/wiki/Dunn_Engineering');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('elder', 'Elder', 'American', 'http://en.wikipedia.org/wiki/Elder_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('sutton', 'Sutton', 'American', 'http://en.wikipedia.org/wiki/Sutton_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('fry', 'Fry', 'British', 'http://en.wikipedia.org/wiki/Fry_(racing_team)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('tec-mec', 'Tec-Mec', 'Italian', 'http://en.wikipedia.org/wiki/Tec-Mec');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('connaught', 'Connaught', 'British', 'http://en.wikipedia.org/wiki/Connaught_Engineering');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('alta', 'Alta', 'British', 'http://en.wikipedia.org/wiki/Alta_auto_racing_team');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('osca', 'OSCA', 'Italian', 'http://en.wikipedia.org/wiki/Officine_Specializate_Costruzione_Automobili');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('gordini', 'Gordini', 'French', 'http://en.wikipedia.org/wiki/Gordini');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('stevens', 'Stevens', 'American', 'http://en.wikipedia.org/wiki/Stevens_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('bugatti', 'Bugatti', 'French', 'http://en.wikipedia.org/wiki/Bugatti');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('mercedes', 'Mercedes', 'German', 'http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lancia', 'Lancia', 'Italian', 'http://en.wikipedia.org/wiki/Lancia_in_Formula_One');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('hwm', 'HWM', 'British', 'http://en.wikipedia.org/wiki/Hersham_and_Walton_Motors');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('schroeder', 'Schroeder', 'American', 'http://en.wikipedia.org/wiki/Schroeder_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('pawl', 'Pawl', 'American', 'http://en.wikipedia.org/wiki/Pawl_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('pankratz', 'Pankratz', 'American', 'http://en.wikipedia.org/wiki/Pankratz');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('arzani-volpini', 'Arzani-Volpini', 'Italian', 'http://en.wikipedia.org/wiki/Arzani-Volpini');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('nichels', 'Nichels', 'American', 'http://en.wikipedia.org/wiki/Nichels');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('bromme', 'Bromme', 'American', 'http://en.wikipedia.org/wiki/Bromme');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('klenk', 'Klenk', 'German', 'http://en.wikipedia.org/wiki/Klenk');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('simca', 'Simca', 'French', 'http://en.wikipedia.org/wiki/Simca');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('turner', 'Turner', 'American', 'http://en.wikipedia.org/wiki/Turner_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('del_roy', 'Del Roy', 'American', 'http://en.wikipedia.org/wiki/Del_Roy');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('veritas', 'Veritas', 'German', 'http://en.wikipedia.org/wiki/Veritas_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('bmw', 'BMW', 'German', 'http://en.wikipedia.org/wiki/BMW');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('emw', 'EMW', 'East German', 'http://en.wikipedia.org/wiki/Eisenacher_Motorenwerk');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('afm', 'AFM', 'German', 'http://en.wikipedia.org/wiki/Alex_von_Falkenhausen_Motorenbau');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('frazer_nash', 'Frazer Nash', 'British', 'http://en.wikipedia.org/wiki/Frazer_Nash');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('sherman', 'Sherman', 'American', 'http://en.wikipedia.org/wiki/Sherman_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('deidt', 'Deidt', 'American', 'http://en.wikipedia.org/wiki/Deidt');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('era', 'ERA', 'British', 'http://en.wikipedia.org/wiki/English_Racing_Automobiles');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('butterworth', 'Aston Butterworth', 'British', 'http://en.wikipedia.org/wiki/Aston_Butterworth');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cisitalia', 'Cisitalia', 'Italian', 'http://en.wikipedia.org/wiki/Cisitalia');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lago', 'Talbot-Lago', 'French', 'http://en.wikipedia.org/wiki/Talbot-Lago');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('hall', 'Hall', 'American', 'http://en.wikipedia.org/wiki/Hall_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('marchese', 'Marchese', 'American', 'http://en.wikipedia.org/wiki/Marchese_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('langley', 'Langley', 'American', 'http://en.wikipedia.org/wiki/Langley_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('rae', 'Rae', 'American', 'http://en.wikipedia.org/wiki/Rae_(motorsport)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('olson', 'Olson', 'American', 'http://en.wikipedia.org/wiki/Olson_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('wetteroth', 'Wetteroth', 'American', 'http://en.wikipedia.org/wiki/Wetteroth');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('adams', 'Adams', 'American', 'http://en.wikipedia.org/wiki/Adams_(constructor)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('snowberger', 'Snowberger', 'American', 'http://en.wikipedia.org/wiki/Snowberger');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('milano', 'Milano', 'Italian', 'http://en.wikipedia.org/wiki/Scuderia_Milano');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('hrt', 'HRT', 'Spanish', 'http://en.wikipedia.org/wiki/Hispania_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-maserati', 'Cooper-Maserati', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('virgin', 'Virgin', 'British', 'http://en.wikipedia.org/wiki/Virgin_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-osca', 'Cooper-OSCA', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-borgward', 'Cooper-Borgward', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-climax', 'Cooper-Climax', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-castellotti', 'Cooper-Castellotti', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lotus-climax', 'Lotus-Climax', 'British', 'http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lotus-maserati', 'Lotus-Maserati', 'British', 'http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('de_tomaso-osca', 'De Tomaso-Osca', 'Italian', 'http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('de_tomaso-alfa_romeo', 'De Tomaso-Alfa Romeo', 'Italian', 'http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lotus-brm', 'Lotus-BRM', 'British', 'http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lotus-borgward', 'Lotus-Borgward', 'British', 'http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-alfa_romeo', 'Cooper-Alfa Romeo', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('de_tomaso-ferrari', 'De Tomaso-Ferrari', 'Italian', 'http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lotus-ford', 'Lotus-Ford', 'British', 'http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brabham-brm', 'Brabham-BRM', 'British', 'http://en.wikipedia.org/wiki/Brabham');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brabham-ford', 'Brabham-Ford', 'British', 'http://en.wikipedia.org/wiki/Brabham');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brabham-climax', 'Brabham-Climax', 'British', 'http://en.wikipedia.org/wiki/Brabham');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lds-climax', 'LDS-Climax', 'South African', 'http://en.wikipedia.org/wiki/LDS_(automobile)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lds-alfa_romeo', 'LDS-Alfa Romeo', 'South African', 'http://en.wikipedia.org/wiki/LDS_(automobile)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-ford', 'Cooper-Ford', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('mclaren-ford', 'McLaren-Ford', 'British', 'http://en.wikipedia.org/wiki/Team_McLaren');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('mclaren-seren', 'McLaren-Serenissima', 'British', 'http://en.wikipedia.org/wiki/Team_McLaren');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('eagle-climax', 'Eagle-Climax', 'American', 'http://en.wikipedia.org/wiki/Anglo_American_Racers');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('eagle-weslake', 'Eagle-Weslake', 'American', 'http://en.wikipedia.org/wiki/Anglo_American_Racers');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brabham-repco', 'Brabham-Repco', 'British', 'http://en.wikipedia.org/wiki/Brabham');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-ferrari', 'Cooper-Ferrari', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-ats', 'Cooper-ATS', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('mclaren-brm', 'McLaren-BRM', 'British', 'http://en.wikipedia.org/wiki/McLaren_(racing)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('cooper-brm', 'Cooper-BRM', 'British', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('matra-ford', 'Matra-Ford', 'French', 'http://en.wikipedia.org/wiki/Matra');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brm-ford', 'BRM-Ford', 'British', 'http://en.wikipedia.org/wiki/BRM');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('mclaren-alfa_romeo', 'McLaren-Alfa Romeo', 'British', 'http://en.wikipedia.org/wiki/McLaren_(racing)');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('march-alfa_romeo', 'March-Alfa Romeo', 'British', 'http://en.wikipedia.org/wiki/March_Engineering');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('march-ford', 'March-Ford', 'British', 'http://en.wikipedia.org/wiki/March_Engineering');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lotus-pw', 'Lotus-Pratt &amp; Whitney', 'British', 'http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('shadow-ford', 'Shadow-Ford', 'British', 'http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('shadow-matra', 'Shadow-Matra', 'British', 'http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('brabham-alfa_romeo', 'Brabham-Alfa Romeo', 'British', 'http://en.wikipedia.org/wiki/Brabham');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lotus_racing', 'Lotus', 'Malaysian', 'http://en.wikipedia.org/wiki/Lotus_Racing');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('marussia', 'Marussia', 'Russian', 'http://en.wikipedia.org/wiki/Marussia_F1');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('caterham', 'Caterham', 'Malaysian', 'http://en.wikipedia.org/wiki/Caterham_F1');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('lotus_f1', 'Lotus F1', 'British', 'http://en.wikipedia.org/wiki/Lotus_F1');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('manor', 'Manor Marussia', 'British', 'http://en.wikipedia.org/wiki/Manor_Motorsport');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('haas', 'Haas F1 Team', 'American', 'http://en.wikipedia.org/wiki/Haas_F1_Team');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('racing_point', 'Racing Point', 'British', 'http://en.wikipedia.org/wiki/Racing_Point_F1_Team');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('alphatauri', 'AlphaTauri', 'Italian', 'http://en.wikipedia.org/wiki/Scuderia_AlphaTauri');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('alpine', 'Alpine F1 Team', 'French', 'http://en.wikipedia.org/wiki/Alpine_F1_Team');
INSERT INTO constructors (constructorsRef, name, nationality, url) VALUES ('rb', 'RB F1 Team', 'Italian', 'http://en.wikipedia.org/wiki/RB_Formula_One_Team');
